#!/bin/bash

# assemble boot
i686-elf-as boot.s -o boot.o

# Compile kernel
i686-elf-gcc -c kernel.c -o kernel.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra

# Link kernel and boot
i686-elf-gcc -T linker.ld -o myos -ffreestanding -O2 -nostdlib boot.o kernel.o -lgcc

# Makes the .iso image
cp myos isodir/boot/myos
grub-mkrescue -o myos.iso isodir

# Runs vm
qemu-system-i386 -cdrom myos.iso
